#!/usr/bin/env bash

CUR="`pwd`"   # save the current directory, so can change back after startup

if [ "x$CUR" = "x" ]; then
    echo "**************************************************************"
    echo " Error: the current working directory does not exist. Please  "
    echo " run FEMhub again from an existing directory.                   "
    echo "**************************************************************"
    exit 1
fi

SAGE_ROOT=`readlink -n "$0" 2> /dev/null` || \
SAGE_ROOT=`realpath    "$0" 2> /dev/null` || \
SAGE_ROOT="$0"

SAGE_ROOT="${SAGE_ROOT%/*}/"

# Make root absolute:
cd "$SAGE_ROOT"
SAGE_ROOT=`pwd`
export SAGE_ROOT
export CUR

if [ ! -f "$SAGE_ROOT/local/bin/python" ]; then
    PYTHON=
    FEMHUB_SYSTEMWIDE_PYTHON="yes"
else
    PYTHON="$SAGE_ROOT/local/bin/python "
    FEMHUB_SYSTEMWIDE_PYTHON="no"
    # this might or might not be necessary:
    #. "$SAGE_ROOT/local/bin/sage-env"
fi
export FEMHUB_SYSTEMWIDE_PYTHON

$PYTHON"$SAGE_ROOT/spkg/base/femhub-run" "$@"
