#!/usr/bin/env bash

CUR="`pwd`"   # save the current directory, so can change back after startup

if [ "x$CUR" = "x" ]; then
    echo "**************************************************************"
    echo " Error: the current working directory does not exist. Please  "
    echo " run FEMhub again from an existing directory.                   "
    echo "**************************************************************"
    exit 1
fi

FEMHUB_ROOT=`readlink -n "$0" 2> /dev/null` || \
FEMHUB_ROOT=`realpath    "$0" 2> /dev/null` || \
FEMHUB_ROOT="$0"

FEMHUB_ROOT="${FEMHUB_ROOT%/*}/"

# Make root absolute:
cd "$FEMHUB_ROOT"
FEMHUB_ROOT=`pwd`
export FEMHUB_ROOT
export CUR

if [ ! -f "$FEMHUB_ROOT/local/bin/python" ]; then
    PYTHON=
    FEMHUB_SYSTEMWIDE_PYTHON="yes"
else
    PYTHON="$FEMHUB_ROOT/local/bin/python "
    FEMHUB_SYSTEMWIDE_PYTHON="no"
    # this is necessary to reset the PYTHONPATH and other stuff:
    . "$FEMHUB_ROOT/local/bin/femhub-env"
fi
export FEMHUB_SYSTEMWIDE_PYTHON

$PYTHON"$FEMHUB_ROOT/spkg/base/femhub_run.py" "$@"
