#! /bin/sh

# Packages are copied from various sources (see the *_STANDARD variables below).
# You can also check (and update) the versions on the web:
#
# Sage: http://www.sagemath.org/packages/standard
# SPD: http://code.google.com/p/spdproject/downloads/list
# FEMhub: http://code.google.com/p/femhub/downloads/list
#
# The idea is to copy most of the packages verbatim from Sage, only if we need
# to do some FEMhub modifications, we provide our own packages.

SAGE_STANDARD=http://www.sagemath.org/packages/standard
SPD_STANDARD=http://spdproject.googlecode.com/files
FEMHUB_STANDARD=http://femhub.googlecode.com/files

if [ `uname` = 'Darwin' ]; then
    WGET="curl -O"
else
    WGET="wget -nc"
fi


# SPD minimum:
$WGET $SAGE_STANDARD/termcap-1.3.1.p1.spkg
$WGET $SAGE_STANDARD/zlib-1.2.3.p5.spkg
$WGET $FEMHUB_STANDARD/readline-6.0.spkg
$WGET $SAGE_STANDARD/python-2.6.4.p7.spkg
$WGET $SPD_STANDARD/ipython-bzr1174.spkg
$WGET $SAGE_STANDARD/cython-0.12.1.spkg

# notebook:
$WGET $SPD_STANDARD/pexpect-2.0.p3.spkg
$WGET $SAGE_STANDARD/twisted-9.0.p2.spkg
$WGET $FEMHUB_STANDARD/setuptools-0.6c11.p0.spkg
$WGET $SAGE_STANDARD/jinja-1.2.p0.spkg
$WGET $FEMHUB_STANDARD/libgpg_error-1.6.p2.spkg
$WGET $FEMHUB_STANDARD/libgcrypt-1.4.3.p2.spkg
$WGET $FEMHUB_STANDARD/gnutls-2.2.1.p3.spkg
$WGET $SAGE_STANDARD/python_gnutls-1.1.4.p7.spkg
$WGET $SAGE_STANDARD/docutils-0.5.p0.spkg
$WGET $SAGE_STANDARD/pygments-0.11.1.p0.spkg
$WGET $SAGE_STANDARD/sphinx-0.6.3.p4.spkg
$WGET $FEMHUB_STANDARD/femhub-lab-0a6225f.spkg

# numpy, scipy matplotlib and sympy
$WGET $FEMHUB_STANDARD/fortran-20071120.p8.spkg
$WGET $SAGE_STANDARD/lapack-20071123.p1.spkg
$WGET $SAGE_STANDARD/blas-20070724.spkg
#$WGET $SAGE_STANDARD/atlas-3.8.3.p9.spkg
$WGET $FEMHUB_STANDARD/numpy-1.3.0.p2.spkg
$WGET $SAGE_STANDARD/scipy-0.7.p4.spkg
$WGET $SAGE_STANDARD/freetype-2.3.5.p2.spkg
$WGET $SAGE_STANDARD/libpng-1.2.35.p0.spkg
$WGET $FEMHUB_STANDARD/matplotlib-0.99.1.p4.spkg
$WGET $FEMHUB_STANDARD/sympy-5d78c29.spkg

# femhub things:
$WGET $FEMHUB_STANDARD/cmake-2.6.2.p1.spkg
$WGET $FEMHUB_STANDARD/judy-1.0.5.p1.spkg
$WGET $FEMHUB_STANDARD/mesa-7.4.4.p3.spkg
$WGET $FEMHUB_STANDARD/vtk-cvs-20090316-minimal.p6.spkg
$WGET $FEMHUB_STANDARD/configobj-4.5.3.spkg
$WGET $FEMHUB_STANDARD/mayavi-3.3.1.p2.spkg
$WGET $FEMHUB_STANDARD/pyparsing-1.5.2.spkg
$WGET $FEMHUB_STANDARD/swig-1.3.36.spkg
$WGET $FEMHUB_STANDARD/sfepy-2010.1.spkg
$WGET $FEMHUB_STANDARD/hermes2d-b1effaa.spkg
$WGET $FEMHUB_STANDARD/pysparse-1.1-6301cea.spkg
$WGET $FEMHUB_STANDARD/fipy-2.1-51f1360.spkg
$WGET $FEMHUB_STANDARD/libfemhub-fd69aca.spkg
