#! /usr/bin/env python

import os
from glob import glob
from os.path import expandvars
from optparse import OptionParser

class CmdException(Exception):
    pass

def main():
    systemwide_python = (os.environ["FEMHUB_SYSTEMWIDE_PYTHON"] == "yes")
    if systemwide_python:
        print """\
***************************************************
FEMhub is not installed. Running systemwide Python.
Only use this mode to install FEMhub.
***************************************************"""

    parser = OptionParser(usage="[options] args")
    parser.add_option("-i", "--install",
            action="store", type="str", dest="install", metavar="PACKAGE",
            default="", help="install a spkg package")
    parser.add_option("-d", "--download_packages",
            action="store_true", dest="download",
            default=False, help="download standard spkg packages")
    parser.add_option("-b", "--build",
            action="store_true", dest="build",
            default=False, help="build FEMhub")
    parser.add_option("-j",
            action="store", type="int", dest="cpu_count", metavar="NCPU",
            default=0, help="number of cpu to use (0 = all)")
    parser.add_option("--shell",
            action="store_true", dest="shell",
            default=False, help="starts a FEMhub shell")
    parser.add_option("-s", "--script",
            action="store", type="str", dest="script", metavar="SCRIPT",
            default=None, help="runs '/bin/bash SCRIPT' in a FEMhub shell")
    options, args = parser.parse_args()
    if options.download:
        download_packages()
        return
    if options.install:
        install_package(options.install, cpu_count=options.cpu_count)
        return
    if options.build:
        build(cpu_count=options.cpu_count)
        return
    if options.shell:
        print "Type CTRL-D to exit the FEMhub shell."
        cmd("/bin/bash --rcfile $SAGE_ROOT/spkg/base/femhub-shell-rc")
        return
    if options.script:
        setup_cpu(options.cpu_count)
        cmd("cd $CUR; /bin/bash " + options.script)
        return
    if systemwide_python:
        parser.print_help()
    else:
        start_femhub()

def setup_cpu(cpu_count):
    if cpu_count == 0:
        try:
            import multiprocessing
            cpu_count = multiprocessing.cpu_count() + 1
        except ImportError:
            cpu_count = 1
    if cpu_count > 1:
        os.environ["MAKE"] = "make -j %d" % cpu_count

def cmd(s):
    s = expandvars(s)
    r = os.system(s)
    if r != 0:
        raise CmdException("Command '%s' failed with err=%d." % (s, r))

def start_femhub(debug=False):
    if debug:
        print "Loading IPython..."
    try:
        import IPython
    except ImportError:
        raise Exception("You need to install 'ipython'")
    if debug:
        print "  Done."
    banner = """\
----------------------------------------------------------------------
| FEMhub Version 0.9.9, Release Date: 2010-05-05                     |
"""
    try:
        import sagenb
        namespace = "yes"
        banner += "| Type lab() for the GUI.                                            |\n"
    except ImportError:
        banner += "| Install the 'femhub-lab' package to enable the lab() command.      |\n"
        namespace = {}
    banner += "----------------------------------------------------------------------\n"
    if namespace == "yes":
        def lab_wrapper(*args, **kwargs):
            from sagenb.notebook.notebook_object import lab
            lab(*args, **kwargs)
        namespace = {"lab": lab_wrapper}

    os.environ["IPYTHONDIR"] = expandvars("$DOT_SAGE/ipython")
    os.environ["IPYTHONRC"] = "ipythonrc"
    if not os.path.exists(os.environ["IPYTHONRC"]):
        cmd('mkdir -p "$DOT_SAGE"')
        cmd('cp -r "$SAGE_ROOT/spkg/base/ipython" "$DOT_SAGE/"')
    os.environ["MPLCONFIGDIR"] = expandvars("$DOT_SAGE/matplotlib")
    if not os.path.exists(os.environ["MPLCONFIGDIR"]):
        cmd('cp -r "$SAGE_ROOT/spkg/base/matplotlib" "$DOT_SAGE/"')

    if debug:
        print "Starting the main loop..."
    IPython.Shell.start(user_ns=namespace).mainloop(banner=banner)

def download_packages():
    print "Downloading standard spkg packages"
    cmd("mkdir -p $SAGE_ROOT/spkg/standard")
    packages = get_standard_packages()
    for p in packages:
        cmd("cd $SAGE_ROOT/spkg/standard; ../base/femhub-wget %s" % p)

def install_package(pkg, install_dependencies=True, force_install=False,
        cpu_count=0):
    """
    Installs the package "pkg".

    "pkg" can be either a full path, or just the name of the package (with or
    without a version).

    "install_dependencies" ... if True, it will also install all dependencies

    "force_install" ... if True, it will install the package even if it has
                    been already installed

    "cpu_count" ... number of processors to use (0 means the number of
            processors in the  machine)

    Examples:

    >>> install_package("spkg/standard/readline-6.0.spkg")
    >>> install_package("readline-6.0.spkg")
    >>> install_package("readline")

    """
    pkg = pkg_make_absolute(pkg)
    if is_installed(pkg):
        if not force_install:
            print "Package '%s' is already installed" % pkg_make_relative(pkg)
            return
    if install_dependencies:
        print "Installing dependencies for %s..." % pkg
        for dep in get_dependencies(pkg):
            install_package(dep, install_dependencies=False,
                    cpu_count=cpu_count)
    print "Installing %s..." % pkg
    femhub_scripts = ["sage-env", "sage-make_relative"]
    setup_cpu(cpu_count)
    cmd("mkdir -p $SAGE_ROOT/local/bin")
    for script in femhub_scripts:
        cmd("cp $SAGE_ROOT/spkg/base/%s $SAGE_ROOT/local/bin/" % script)
    cmd("$SAGE_ROOT/spkg/base/sage-spkg %s" % pkg)
    cmd("touch $SAGE_ROOT/spkg/installed/%s" % pkg_make_relative(pkg))

def is_installed(pkg):
    pkg = pkg_make_relative(pkg)
    candidates = glob(expandvars("$SAGE_ROOT/spkg/installed/%s" % pkg))
    if len(candidates) == 1:
        return True
    elif len(candidates) == 0:
        return False
    else:
        raise Exception("Internal error: got more candidates in is_installed")

def pkg_make_absolute(pkg):
    if os.path.exists(pkg):
        return pkg

    pkg_default = "$SAGE_ROOT/spkg/standard"
    if os.path.exists(pkg_default):
        return pkg_default

    candidates = glob(expandvars("$SAGE_ROOT/spkg/standard/%s-*.spkg" % \
            pkg))
    if len(candidates) == 0:
        candidates = glob(expandvars("$SAGE_ROOT/spkg/standard/%s*.spkg" % \
            pkg))
    if len(candidates) == 0:
        raise Exception("Package not found")
    if len(candidates) == 1:
        return candidates[0]
    standard_packages = get_standard_packages(just_names=True)
    for p in candidates:
        if os.path.split(p)[1] in standard_packages:
            return p

    print "Too many candidates:"
    print "    " + "\n    ".join(candidates)

    raise Exception("Ambiguous package name.")

def pkg_make_relative(pkg):
    pkg = pkg_make_absolute(pkg)
    # This is quite robust:
    pkg_with_version = pkg[pkg.rfind("/")+1:pkg.rfind(".spkg")]
    # This might be a bit fragile:
    pkg_name = pkg_with_version[:pkg_with_version.find("-")]
    return pkg_name

def make_unique(l):
    m = []
    for item in l:
        if item not in m:
            m.append(item)
    return m

def get_dependencies(pkg):
    """
    Gets all (including indirect) dependencies for the package "pkg".

    For simplicity, the dependency graph is currently hardwired in this
    function.
    """
    pkg_name = pkg_make_relative(pkg)
    dependency_graph = {
            "python": ["termcap", "zlib", "readline", "bzip2"],
            "ipython": ["python"],
            "cython": ["python"],
            "sympy": ["python"],
            "lapack": ["fortran"],
            "blas": ["fortran", "lapack"],
            "numpy": ["python", "lapack", "blas"],
            "scipy": ["numpy"],
            "matplotlib": ["freetype", "libpng", "python"],
            "hermes2d": ["cmake", "scipy", "judy", "cython", "matplotlib"],
            "vtk": ["mesa", "cmake"],
            "mayavi": ["python", "configobj", "vtk"],
            "pyparsing": ["python"],
            "pysparse": ["python"],
            "swig": ["python"],
            "sfepy": ["swig", "scipy"],
            "fipy": ["python", "pysparse", "setuptools"],
            "libfemhub": ["python"],
            "python_gnutls": ["gnutls"],
            # TODO: fix "-" in package names (look at how Debian does it)
            # This is actually a femhub-lab:
            "femhub": ["pexpect", "twisted", "setuptools",
                "jinja", "libgpg_error", "libgcrypt", "python_gnutls",
                "docutils", "pygments",
                "jinja2",
                "sphinx",
                ],
            }
    deps = []
    for dep in dependency_graph.get(pkg_name, []):
        deps.extend(get_dependencies(dep))
        deps.append(dep)
    deps = make_unique(deps)
    return deps

def get_standard_packages(just_names=False):
    """
    Returns the list of standard packages.

    just_names ... if True, only the names of the packages are returned

    Packages are copied from various sources (see the *_STANDARD variables
    below).  You can also check (and update) the versions on the web:

    Sage: http://www.sagemath.org/packages/standard
    FEMhub: http://femhub.org/stpack

    The idea is to copy most of the packages verbatim from Sage, only if we
    need to do some FEMhub modifications, we provide our own packages.

    """

    SAGE_STANDARD =   "http://www.sagemath.org/packages/standard"
    FEMHUB_STANDARD = "http://femhub.org/stpack"

    sage_packages = [
            "termcap-1.3.1.p1",
            "zlib-1.2.3.p5",
            "python-2.6.4.p8",
            "cython-0.12.1",
            "twisted-9.0.p2",
            "jinja-1.2.p0",
            "jinja2-2.1.1.p0",
            "python_gnutls-1.1.4.p7",
            "docutils-0.5.p0",
            "pygments-0.11.1.p0",
            "sphinx-0.6.3.p4",
            "lapack-20071123.p1",
            "blas-20070724",
            "scipy-0.7.p5",
            "freetype-2.3.5.p2",
            "libpng-1.2.35.p1",
            ]

    femhub_packages = [
            "ipython-bzr1174",
            "readline-6.0",
            "bzip2-1.0.5",
            "pexpect-2.0.p3",
            "setuptools-0.6c11.p0",
            "libgpg_error-1.6.p2",
            "libgcrypt-1.4.3.p2",
            "gnutls-2.2.1.p3",
            "femhub-lab-2ffaa67",

            "fortran-20071120.p8",
            "numpy-1.3.0.p2",
            "matplotlib-0.99.1.p4",
            "sympy-5d78c29",

            "cmake-2.8.1.p2",
            "judy-1.0.5.p1",
            "mesa-7.4.4.p3",
            "vtk-cvs-20090316-minimal.p6",
            "configobj-4.5.3",
            "mayavi-3.3.1.p2",
            "pyparsing-1.5.2",
            "swig-1.3.36",
            "sfepy-2010.1",
            "hermes2d-ee3e3ab",
            "pysparse-1.1-6301cea",
            "fipy-2.1-51f1360",
            "libfemhub-05e3941",
            ]

    if just_names:
        packages = \
                [p + ".spkg" for p in sage_packages] + \
                [p + ".spkg" for p in femhub_packages]
    else:
        packages = \
                [SAGE_STANDARD   + "/" + p + ".spkg" for p in sage_packages] + \
                [FEMHUB_STANDARD + "/" + p + ".spkg" for p in femhub_packages]
    return packages

def build(cpu_count=0):
    print "Building FEMhub"
    # Only add the packages that you want to have in FEMhub. Don't add
    # dependencies (those are handled in the get_dependencies() function)
    packages_list = [
            "ipython",
            "hermes2d",
            # requires: setupdocs>=1.0, doesn't work without a net...
            #"mayavi",
            "libfemhub",
            "fipy",
            "sfepy",
            "sympy",
            "femhub-lab",
            ]
    for pkg in packages_list:
        install_package(pkg, cpu_count=cpu_count)
    print
    print "Finished building FEMhub."

if __name__ == "__main__":
    main()
