#! /usr/bin/env python

import os
from glob import glob
from os.path import expandvars
from optparse import OptionParser

class CmdException(Exception):
    pass

def main():
    systemwide_python = (os.environ["FEMHUB_SYSTEMWIDE_PYTHON"] == "yes")
    if systemwide_python:
        print """\
***************************************************
FEMhub is not installed. Running systemwide Python.
Only use this mode to install FEMhub."
***************************************************"""

    parser = OptionParser(usage="[options] args")
    parser.add_option("-i", "--install",
            action="store", type="str", dest="install", metavar="PACKAGE",
            default="", help="install a spkg package")
    parser.add_option("-d", "--download_packages",
            action="store_true", dest="download",
            default=False, help="download standard spkg packages")
    parser.add_option("-b", "--build",
            action="store_true", dest="build",
            default=False, help="build FEMhub")
    options, args = parser.parse_args()
    if options.download:
        download_packages()
        return
    if options.install:
        install_package(options.install)
        return
    if options.build:
        build()
        return
    if systemwide_python:
        parser.print_help()
    else:
        import IPython
        IPython.ipapi.launch_new_instance()

def cmd(s):
    r = os.system(s)
    if r != 0:
        raise CmdException("Command '%s' failed with err=%d." % (s, r))

def download_packages():
    print "Downloading standard spkg packages"
    cmd("cd $SAGE_ROOT/spkg/standard; ./download_packages")


def install_package(pkg):
    """
    Installs the package "pkg".

    "pkg" can be either a full path, or just the name of the package (with or
    without a version).

    Examples:

    >>>install_package("spkg/standard/readline-6.0.spkg")
    >>>install_package("readline-6.0.spkg")
    >>>install_package("readline")

    """
    pkg = pkg_make_absolute(pkg)
    print "Installing %s..." % pkg
    femhub_scripts = ["sage-env", "sage-make_relative"]
    try:
        import multiprocessing
        cpu_count = multiprocessing.cpu_count()
    except ImportError:
        cpu_count = 1
    try:
        cmd("mkdir -p $SAGE_ROOT/local/bin")
        for script in femhub_scripts:
            cmd("cp $SAGE_ROOT/spkg/base/%s $SAGE_ROOT/local/bin/" % script)
        if cpu_count > 1:
            os.environ["MAKE"] = "make -j %d" % (cpu_count + 1)
        cmd("$SAGE_ROOT/spkg/base/sage-spkg %s" % pkg)
    except CmdException as e:
        print e

def pkg_make_absolute(pkg):
    if os.path.exists(pkg):
        return pkg

    pkg_default = "$SAGE_ROOT/spkg/standard"
    if os.path.exists(pkg_default):
        return pkg_default

    candidates = glob(expandvars("$SAGE_ROOT/spkg/standard/%s-*.spkg" % \
            pkg))
    if len(candidates) == 0:
        candidates = glob(expandvars("$SAGE_ROOT/spkg/standard/%s*.spkg" % \
            pkg))
    if len(candidates) == 1:
        return candidates[0]
    else:
        print "Too many candidates:"
        print "    " + "\n    ".join(candidates)

    raise Exception("Unknown package")

def build():
    print "Building FEMhub"
    base_list = [
            "termcap",
            "zlib",
            "readline",
            "python",
            "ipython",
            "cython",
            "sympy",

            "fortran",
            "lapack",
            "blas",
            "freetype",
            "libpng",
            "numpy",
            "scipy",
            "matplotlib",

            "cmake",
            "hermes2d",
        ]
    other = [
            "pexpect",
            "twisted",
            "setuptools",
            "jinja",
            "libgpg_error",
            "libgcrypt",
            "gnutls",
            "python_gnutls",
            "docutils",
            "pygments",
            "sphinx",
            "femhub-lab",


            "judy",
            "mesa",
            "vtk-cvs",
            "configobj",
            "mayavi",
            "pyparsing",
            "swig",
            "sfepy",
            "pysparse",
            "fipy",
            "libfemhub",
            ]
    packages_list = base_list
    for pkg in packages_list:
        install_package(pkg)
    print
    print "Finished building FEMhub."

if __name__ == "__main__":
    main()
