#!/usr/bin/env sh

sage-location

if [ $? -ne 0 ]; then
   echo "Problem with sage location or flags."
   exit 1
fi

echo "Testing that FEMhub starts..."
sage -c "print 'Yes, FEMhub starts.'"

if [ $? -ne 0 ]; then
    echo "FEMhub failed to startup." 
    exit 1
fi
