#!/usr/bin/env python

import os, sys, socket

print open(os.environ['SAGE_ROOT'] + '/local/bin/sage-banner').read()

print "Please wait while the FEMhub Notebook server starts..."

#from sage.server.notebook.all import notebook
from sagenb.notebook.notebook_object import lab 

print "..."

if len(sys.argv) > 1:
    lab(secure=False, *sys.argv[1:])
else:
    lab(port=8000, secure=False)
